create table employees (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  team_name varchar(120) not null,
  position_type varchar(120) not null,
  active boolean not null default true,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create unique index uk_employees_active_name on employees (lower(name)) where active;

create table projects (
  id bigint generated by default as identity primary key,
  name varchar(200) not null,
  customer_name varchar(200),
  industry varchar(120),
  project_stage varchar(80),
  owner_name varchar(120),
  priority varchar(40),
  status varchar(60) not null default 'active',
  code varchar(80),
  formal boolean not null default true,
  system_key varchar(80),
  active boolean not null default true,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uk_projects_code unique (code),
  constraint uk_projects_system_key unique (system_key),
  constraint ck_projects_type check (
    (formal and system_key is null) or (not formal and system_key is not null)
  )
);

create table business_dictionaries (
  id bigint generated by default as identity primary key,
  category varchar(80) not null,
  code varchar(80) not null,
  label varchar(120) not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uk_dictionary_category_code unique (category, code)
);

insert into projects(name, formal, system_key, status) values
  ('客户拓展阶段', false, 'customer-expansion', 'active'),
  ('暂无正式项目', false, 'no-formal-project', 'active'),
  ('内部专项', false, 'internal-initiative', 'active'),
  ('部门日常工作', false, 'department-routine-work', 'active'),
  ('培训学习', false, 'training-learning', 'active'),
  ('其他', false, 'other', 'active');

insert into business_dictionaries(category, code, label, sort_order) values
  ('work_type', 'delivery', '项目交付', 10),
  ('work_type', 'presales', '售前支持', 20),
  ('work_type', 'internal', '内部工作', 30),
  ('risk_type', 'dependency', '外部依赖', 10),
  ('risk_type', 'resource', '资源不足', 20),
  ('risk_type', 'quality', '质量风险', 30),
  ('collaboration_role', 'project-owner', '项目负责人', 10),
  ('collaboration_role', 'technical-expert', '技术专家', 20),
  ('collaboration_role', 'manager', '部门管理者', 30);
