create table analysis_configurations (
  id smallint primary key,
  enabled boolean not null default true,
  cron_expression varchar(120) not null,
  selected_dimensions varchar(500) not null,
  rule_thresholds text not null,
  prompt_version varchar(80) not null,
  prompt_template text not null,
  dashboard_enabled boolean not null default true,
  report_enabled boolean not null default true,
  email_enabled boolean not null default false,
  recipients text,
  cc_recipients text,
  email_subject_template varchar(300) not null,
  report_template text not null,
  model_endpoint varchar(500),
  model_name varchar(160),
  model_api_key_reference varchar(120) not null default 'LLM_API_KEY',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint ck_analysis_configuration_singleton check (id = 1)
);

insert into analysis_configurations(
  id, enabled, cron_expression, selected_dimensions, rule_thresholds,
  prompt_version, prompt_template, email_subject_template, report_template
) values (
  1, true, '0 0 22 * * ?',
  'personnel-efficiency,work-saturation,project-progress,project-risk,resource-collaboration,resource-allocation,report-quality',
  'highTaskCount=6;highProjectCount=3;consecutiveSupportDays=3;waitingFeedbackDays=2;vagueResultLength=8',
  'V1.0',
  '基于客观指标、规则结论和日报任务文本输出管理建议。不得修改数据、调配人员或替代管理决策。',
  '日报分析报告 - {{date}}',
  '<h1>日报分析报告 {{date}}</h1>{{content}}'
);

create table analysis_runs (
  id bigint generated by default as identity primary key,
  analysis_date date not null,
  task_name varchar(160) not null default '每日综合日报分析',
  trigger_type varchar(30) not null,
  status varchar(40) not null,
  selected_dimensions varchar(500) not null,
  started_at timestamptz not null,
  finished_at timestamptz,
  analyzed_employee_count integer not null default 0,
  metrics_json text,
  rules_json text,
  advisory_text text,
  llm_status varchar(40),
  report_html text,
  report_pdf bytea,
  report_file_name varchar(260),
  email_status varchar(40) not null default 'not-requested',
  error_summary text,
  retry_of_run_id bigint references analysis_runs(id),
  retry_count integer not null default 0,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint ck_analysis_run_trigger check (trigger_type in ('scheduled', 'manual', 'retry')),
  constraint ck_analysis_run_status check (status in ('running', 'succeeded', 'partial-failure', 'failed'))
);

create index ix_analysis_runs_date on analysis_runs(analysis_date desc, started_at desc);

create table analysis_dimension_results (
  id bigint generated by default as identity primary key,
  run_id bigint not null references analysis_runs(id) on delete cascade,
  dimension varchar(80) not null,
  result_text text not null,
  created_at timestamptz not null default current_timestamp,
  constraint uk_analysis_dimension_result unique (run_id, dimension)
);

create table email_deliveries (
  id bigint generated by default as identity primary key,
  run_id bigint not null references analysis_runs(id) on delete cascade,
  analysis_date date not null,
  status varchar(40) not null,
  recipients text,
  cc_recipients text,
  subject varchar(300),
  sent_at timestamptz,
  error_summary text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uk_email_delivery_run unique (run_id),
  constraint ck_email_delivery_status check (status in ('skipped', 'sent', 'failed'))
);

create unique index uk_email_delivery_success_date
  on email_deliveries(analysis_date) where status = 'sent';
