create table workday_calendar (
  id bigint generated by default as identity primary key,
  calendar_date date not null,
  workday boolean not null,
  source varchar(40) not null,
  note varchar(500),
  active boolean not null default true,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uk_workday_calendar_date_source unique (calendar_date, source)
);

create index ix_workday_calendar_date_active on workday_calendar(calendar_date) where active;
