create table report_statistics_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_type varchar(20) not null,
  snapshot_date date not null,
  captured_at timestamptz not null,
  expected_count integer not null,
  submitted_count integer not null,
  missing_count integer not null,
  submission_rate numeric(6,4) not null,
  submitted_employees_json text not null,
  missing_employees_json text not null,
  team_statistics_json text not null,
  late_submitted_employees_json text not null,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uk_report_statistics_snapshot_type_date unique (snapshot_type, snapshot_date),
  constraint ck_report_statistics_snapshot_type check (snapshot_type in ('EARLY', 'FINAL')),
  constraint ck_report_statistics_snapshot_counts check (
    expected_count >= 0 and submitted_count >= 0 and missing_count >= 0
    and submitted_count + missing_count = expected_count
  )
);

create index ix_report_statistics_snapshots_date
  on report_statistics_snapshots(snapshot_date desc, captured_at desc);

create table report_statistics_configurations (
  id smallint primary key,
  early_snapshot_enabled boolean not null default true,
  early_snapshot_cron_expression varchar(120) not null,
  final_snapshot_enabled boolean not null default true,
  final_snapshot_cron_expression varchar(120) not null,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint ck_report_statistics_configuration_singleton check (id = 1)
);

insert into report_statistics_configurations(
  id, early_snapshot_enabled, early_snapshot_cron_expression,
  final_snapshot_enabled, final_snapshot_cron_expression
) values (1, true, '0 30 17 ? * MON-FRI', true, '0 0 22 ? * MON-FRI');
