create table analysis_period_configurations (
  analysis_period varchar(20) primary key,
  enabled boolean not null default true,
  cron_expression varchar(120) not null,
  enabled_modules text not null,
  retention_months integer not null default 24,
  include_evidence_in_delivery boolean not null default false,
  updated_at timestamptz not null default current_timestamp,
  constraint ck_analysis_period_configuration_period
    check (analysis_period in ('DAILY', 'WEEKLY', 'MONTHLY')),
  constraint ck_analysis_period_configuration_retention check (retention_months > 0)
);

insert into analysis_period_configurations(
  analysis_period, enabled, cron_expression, enabled_modules, include_evidence_in_delivery
) values
  ('DAILY', true, '0 10 22 ? * MON-FRI',
   'workload,project-progress,risk,collaboration,quality,management-suggestions', true),
  ('WEEKLY', true, '0 20 22 ? * MON-FRI',
   'workload,project-progress,risk,collaboration,quality,management-suggestions', false),
  ('MONTHLY', true, '0 30 22 ? * MON-FRI',
   'workload,project-progress,risk,collaboration,quality,management-suggestions', false);

create table analysis_rule_versions (
  id bigint generated by default as identity primary key,
  analysis_period varchar(20) not null,
  version_number integer not null,
  status varchar(20) not null,
  change_note varchar(1000) not null,
  rules_json text not null,
  prompt_template text not null,
  custom_schema_json text not null default '{}',
  trial_succeeded_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default current_timestamp,
  constraint uk_analysis_rule_version unique (analysis_period, version_number),
  constraint ck_analysis_rule_period check (analysis_period in ('DAILY', 'WEEKLY', 'MONTHLY')),
  constraint ck_analysis_rule_status check (status in ('DRAFT', 'PUBLISHED', 'HISTORICAL'))
);

insert into analysis_rule_versions(
  analysis_period, version_number, status, change_note, rules_json, prompt_template,
  custom_schema_json, trial_succeeded_at, published_at
) values
  ('DAILY', 1, 'PUBLISHED', '系统默认日报规则', '{}', '基于日报任务输出可追溯的 AI 辅助分析。', '{}', current_timestamp, current_timestamp),
  ('WEEKLY', 1, 'PUBLISHED', '系统默认周报规则', '{}', '基于本周日报趋势输出可追溯的 AI 辅助分析。', '{}', current_timestamp, current_timestamp),
  ('MONTHLY', 1, 'PUBLISHED', '系统默认月报规则', '{}', '基于本月日报趋势输出可追溯的 AI 辅助分析。', '{}', current_timestamp, current_timestamp);

alter table analysis_runs
  add column analysis_period varchar(20) not null default 'DAILY',
  add column period_start date,
  add column period_end date,
  add column rule_version_id bigint references analysis_rule_versions(id),
  add column rule_snapshot_json text,
  add column prompt_snapshot text,
  add column schema_snapshot_json text,
  add column source_snapshot_json text,
  add column display_data_json text,
  add column model_name_snapshot varchar(160);

alter table analysis_runs
  add constraint ck_analysis_run_period check (analysis_period in ('DAILY', 'WEEKLY', 'MONTHLY'));

update analysis_runs set period_start=analysis_date, period_end=analysis_date
  where period_start is null;

create index ix_analysis_runs_period_window
  on analysis_runs(analysis_period, period_start desc, period_end desc, started_at desc);
