create table analysis_skill_versions (
  id bigint generated by default as identity primary key,
  analysis_period varchar(20) not null,
  skill_kind varchar(20) not null,
  version_number integer not null,
  status varchar(20) not null,
  skill_name varchar(160) not null,
  description varchar(1000) not null,
  package_name varchar(255) not null,
  package_bytes bytea not null,
  skill_markdown text not null,
  checksum varchar(64) not null,
  validation_message varchar(1000) not null,
  trial_succeeded_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default current_timestamp,
  constraint uk_analysis_skill_version unique (analysis_period, skill_kind, version_number),
  constraint ck_analysis_skill_period
    check (analysis_period in ('DAILY', 'WEEKLY', 'MONTHLY')),
  constraint ck_analysis_skill_kind check (skill_kind in ('RULE', 'TEMPLATE')),
  constraint ck_analysis_skill_status check (status in ('DRAFT', 'PUBLISHED', 'HISTORICAL'))
);

create table analysis_skill_trials (
  id bigint generated by default as identity primary key,
  analysis_period varchar(20) not null,
  rule_skill_version_id bigint not null references analysis_skill_versions(id),
  template_skill_version_id bigint not null references analysis_skill_versions(id),
  period_start date not null,
  period_end date not null,
  status varchar(30) not null,
  source_snapshot_json text not null,
  analysis_draft text,
  rendered_html text,
  error_summary text,
  started_at timestamptz not null default current_timestamp,
  finished_at timestamptz,
  constraint ck_analysis_skill_trial_period
    check (analysis_period in ('DAILY', 'WEEKLY', 'MONTHLY'))
);

alter table analysis_runs
  add column if not exists rule_skill_version_id bigint references analysis_skill_versions(id),
  add column if not exists template_skill_version_id bigint references analysis_skill_versions(id);

create index ix_analysis_skill_versions_slot
  on analysis_skill_versions(analysis_period, skill_kind, version_number desc);
create index ix_analysis_skill_trials_period
  on analysis_skill_trials(analysis_period, period_end desc, started_at desc);
