create table project_state_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null,
  project_id bigint not null references projects(id) on delete cascade,
  project_name varchar(240) not null,
  state varchar(50) not null,
  lifecycle varchar(30),
  current_stage varchar(100),
  state_started_date date not null,
  owner_name varchar(120),
  participant_count integer not null default 0,
  blocked_task_count integer not null default 0,
  latest_report_date date,
  trigger_task_id bigint references daily_tasks(id),
  captured_at timestamptz not null default current_timestamp,
  constraint uk_project_state_snapshot_date_project unique (snapshot_date, project_id)
);

create index ix_project_state_snapshots_date
  on project_state_snapshots(snapshot_date desc, project_id);
