alter table analysis_skill_versions
  add column if not exists runtime_profile varchar(80),
  add column if not exists manifest_json text;

create table if not exists analysis_skill_artifacts (
  id bigint generated by default as identity primary key,
  trial_id bigint not null references analysis_skill_trials(id) on delete cascade,
  artifact_type varchar(32) not null,
  file_name varchar(255) not null,
  mime_type varchar(160) not null,
  checksum varchar(64) not null,
  content bytea not null,
  created_at timestamptz not null default current_timestamp,
  constraint uk_analysis_skill_artifact unique (trial_id, artifact_type)
);

create index if not exists ix_analysis_skill_artifacts_trial
  on analysis_skill_artifacts(trial_id);
